import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Disclaimer',
  description: 'Disclaimer and Legal Terms for Swalekhani AI Official Letterpad Platform.',
  alternates: {
    canonical: '/disclaimer',
  },
};

export default function Disclaimer() {
  return (
    <main className="min-h-screen bg-[#07090f] text-white/80 p-8 pt-24 max-w-4xl mx-auto">
      <h1 className="text-4xl font-bold text-white mb-6">Disclaimer</h1>
      <p className="mb-4">Last updated: {new Date().toLocaleDateString()}</p>
      
      <div className="space-y-6">
        <section>
          <h2 className="text-2xl font-semibold text-white mb-3">1. General Information</h2>
          <p>The information and content generated by Swalekhani is for general informational and drafting purposes only. All information on the Site is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or generated content.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white mb-3">2. AI-Generated Content</h2>
          <p>Swalekhani utilizes Artificial Intelligence (AI) to assist in generating letter drafts. AI-generated text may occasionally be inaccurate, inappropriate, or out of context. It is your sole responsibility to review, verify, and edit all AI-generated content before using it for any official, legal, or professional purposes.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white mb-3">3. Professional Advice</h2>
          <p>The letters generated by this platform do not constitute legal, financial, or professional advice. If you require specific advice or properly binding legal documents, you should consult with an appropriate professional.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white mb-3">4. Unofficial Documents &amp; No Impersonation</h2>
          <p className="mb-3">Templates on Swalekhani that resemble government, legislative, Panchayat, or public-representative letterheads — including any use of the State Emblem of India (Ashoka Lion Capital), &quot;Satyameva Jayate&quot;, ministry names, Sansad seals, or official-style insignia — are <strong className="text-white">unofficial design drafts</strong> created for practice, study, and layout reference only.</p>
          <p className="mb-3">Nothing generated on this platform is issued by the Government of India, any State Government, Parliament, State Legislature, Gram Panchayat, or elected representative. You must not present Swalekhani output as a genuine official document, certificate, or communication, and you must not use it to impersonate any official, authority, or institution.</p>
          <p>Misuse of generated drafts — including forgery, fraud, or misrepresentation of authority — is the user&apos;s sole legal responsibility and may constitute an offence under applicable law, including the State Emblem of India (Prohibition of Improper Use) Act and provisions of the Bharatiya Nyaya Sanhita relating to forgery and cheating.</p>
        </section>
      </div>
    </main>
  );
}
