import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Disclaimer | Swalekhani',
  description: 'Disclaimer and Legal Terms for Swalekhani AI Official Letterpad Platform.',
  alternates: {
    canonical: '/disclaimer',
  },
};

export default function Disclaimer() {
  return (
    <main className="min-h-screen bg-[#07090f] text-white/80 p-8 pt-24 max-w-4xl mx-auto">
      <h1 className="text-4xl font-bold text-white mb-6">Disclaimer</h1>
      <p className="mb-4">Last updated: {new Date().toLocaleDateString()}</p>
      
      <div className="space-y-6">
        <section>
          <h2 className="text-2xl font-semibold text-white mb-3">1. General Information</h2>
          <p>The information and content generated by Swalekhani is for general informational and drafting purposes only. All information on the Site is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or generated content.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white mb-3">2. AI-Generated Content</h2>
          <p>Swalekhani utilizes Artificial Intelligence (AI) to assist in generating letter drafts. AI-generated text may occasionally be inaccurate, inappropriate, or out of context. It is your sole responsibility to review, verify, and edit all AI-generated content before using it for any official, legal, or professional purposes.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white mb-3">3. Professional Advice</h2>
          <p>The letters generated by this platform do not constitute legal, financial, or professional advice. If you require specific advice or properly binding legal documents, you should consult with an appropriate professional.</p>
        </section>
      </div>
    </main>
  );
}
